---
- hosts: local
  gather_facts: False
  tasks:
  - name: install base dependencies
    homebrew_cask:
      name: "{{ item }}"
      state: present
    with_items:
      - java
  - name: install homebrew items
    homebrew:
      name: "{{ item }}"
      state: latest
      update_homebrew: yes
    with_items:
      - nodejs
      - rbenv
      - git
      - git-flow
      - maven
      - docker
      - docker-machine
  - name: install media items
    homebrew_cask:
      name: "{{ item }}"
      state: present
    with_items:
      - spotify
      - spotify-notifications
    tags:
      - media
  - name: install homebrew cask items
    homebrew_cask:
      name: "{{ item }}"
      state: present
    with_items:
      - alfred
      - spectacle
      - atom
      - google-chrome
      - slack
      - controlplane
      - intellij-idea
      - skype-for-business
      - skype
      - skitch
      - tor
      - virtualbox
  - name: install oh-my-zsh
    shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    tags:
      - cli
  - name: rbenv plugins
    shell: git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
    tags:
      - cli
